//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPortal.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESAFETY_PROJECT2
    {
        public ESAFETY_PROJECT2()
        {
            this.ESAFETY_WORKFLOW = new HashSet<ESAFETY_WORKFLOW>();
        }
    
        public int PROJECT2_ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public int SUBMISSION_TYPE_ID { get; set; }
        public string SUBMISSION_NUMBER { get; set; }
        public System.DateTime SUBMISSION_DATE { get; set; }
        public string SDN { get; set; }
        public string EDR_LOCATION { get; set; }
        public string AIM { get; set; }
        public string COMMENTS { get; set; }
    
        public virtual ICollection<ESAFETY_WORKFLOW> ESAFETY_WORKFLOW { get; set; }
    }
}
