//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPortal.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPTOOLS_PROJECT
    {
        public FPTOOLS_PROJECT()
        {
            this.IPORTAL_FP = new HashSet<IPORTAL_FP>();
        }
    
        public int PROJECT_ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public string FILE_NAME { get; set; }
        public int USER_ID { get; set; }
    
        public virtual ICollection<IPORTAL_FP> IPORTAL_FP { get; set; }
        public virtual SYSTEM_USER SYSTEM_USER { get; set; }
    }
}
