//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPortal.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPORTAL_FP
    {
        public IPORTAL_FP()
        {
            this.IPORTAL_FP_ROW = new HashSet<IPORTAL_FP_ROW>();
        }
    
        public int FP_ID { get; set; }
        public string DRUGNAME { get; set; }
        public string TITLE { get; set; }
        public int SCALE_ID { get; set; }
        public string FOOTNOTE { get; set; }
        public string XLABEL { get; set; }
        public int FP_STYLE_ID { get; set; }
        public double RANGE_BOTTOM { get; set; }
        public double RANGE_TOP { get; set; }
        public double RANGE_STEP { get; set; }
        public int PROJECT_ID { get; set; }
    
        public virtual FPTOOLS_PROJECT FPTOOLS_PROJECT { get; set; }
        public virtual IPORTAL_FP_STYLE IPORTAL_FP_STYLE { get; set; }
        public virtual IPORTAL_SCALE IPORTAL_SCALE { get; set; }
        public virtual ICollection<IPORTAL_FP_ROW> IPORTAL_FP_ROW { get; set; }
    }
}
