//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPortal.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPORTAL_SUBMISSION_TYPE
    {
        public IPORTAL_SUBMISSION_TYPE()
        {
            this.IPORTAL_SUBMISSION = new HashSet<IPORTAL_SUBMISSION>();
        }
    
        public int SUBMISSION_TYPE_ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<IPORTAL_SUBMISSION> IPORTAL_SUBMISSION { get; set; }
    }
}
