//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPortal.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPORTAL_FP_ROW
    {
        public int FP_ROW_ID { get; set; }
        public string CATEGORY { get; set; }
        public string SUBCATEGORY { get; set; }
        public string PARAMETER { get; set; }
        public Nullable<double> RATIO { get; set; }
        public Nullable<double> LOWER_CI { get; set; }
        public Nullable<double> UPPER_CI { get; set; }
        public string COMMENT { get; set; }
        public int FP_ID { get; set; }
    
        public virtual IPORTAL_FP IPORTAL_FP { get; set; }
    }
}
