//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPortal.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPORTAL_FILE
    {
        public IPORTAL_FILE()
        {
            this.IPORTAL_DM_FILE = new HashSet<IPORTAL_DM_FILE>();
            this.IPORTAL_EX_FILE = new HashSet<IPORTAL_EX_FILE>();
            this.IPORTAL_PC_FILE = new HashSet<IPORTAL_PC_FILE>();
            this.IPORTAL_PP_FILE = new HashSet<IPORTAL_PP_FILE>();
            this.IPORTAL_VARIABLE_MAPPING = new HashSet<IPORTAL_VARIABLE_MAPPING>();
        }
    
        public int FILE_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string SERVER_PATH { get; set; }
        public string FAST_CHECKSUM { get; set; }
    
        public virtual ICollection<IPORTAL_DM_FILE> IPORTAL_DM_FILE { get; set; }
        public virtual ICollection<IPORTAL_EX_FILE> IPORTAL_EX_FILE { get; set; }
        public virtual ICollection<IPORTAL_PC_FILE> IPORTAL_PC_FILE { get; set; }
        public virtual ICollection<IPORTAL_PP_FILE> IPORTAL_PP_FILE { get; set; }
        public virtual ICollection<IPORTAL_VARIABLE_MAPPING> IPORTAL_VARIABLE_MAPPING { get; set; }
    }
}
