//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPortal.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPORTAL_STUDY_DESIGN
    {
        public IPORTAL_STUDY_DESIGN()
        {
            this.IPORTAL_STUDY = new HashSet<IPORTAL_STUDY>();
        }
    
        public int STUDY_DESIGN_ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<IPORTAL_STUDY> IPORTAL_STUDY { get; set; }
    }
}
