//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPortal.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPORTAL_SUBMISSION
    {
        public IPORTAL_SUBMISSION()
        {
            this.IPORTAL_STUDY = new HashSet<IPORTAL_STUDY>();
        }
    
        public int SUBMISSION_ID { get; set; }
        public string SUBMISSION_CODE { get; set; }
        public int SUBMISSION_TYPE_ID { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<IPORTAL_STUDY> IPORTAL_STUDY { get; set; }
        public virtual IPORTAL_SUBMISSION_TYPE IPORTAL_SUBMISSION_TYPE { get; set; }
    }
}
