//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPortal.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OCPSQLEntities : DbContext
    {
        public OCPSQLEntities()
            : base("name=OCPSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ESAFETY_PROJECT> ESAFETY_PROJECT { get; set; }
        public DbSet<ESAFETY_PROJECT2> ESAFETY_PROJECT2 { get; set; }
        public DbSet<ESAFETY_WORKFLOW> ESAFETY_WORKFLOW { get; set; }
        public DbSet<FPTOOLS_PROJECT> FPTOOLS_PROJECT { get; set; }
        public DbSet<IPORTAL_DM_DATASET> IPORTAL_DM_DATASET { get; set; }
        public DbSet<IPORTAL_DM_FILE> IPORTAL_DM_FILE { get; set; }
        public DbSet<IPORTAL_EX_DATASET> IPORTAL_EX_DATASET { get; set; }
        public DbSet<IPORTAL_EX_FILE> IPORTAL_EX_FILE { get; set; }
        public DbSet<IPORTAL_FILE> IPORTAL_FILE { get; set; }
        public DbSet<IPORTAL_FP> IPORTAL_FP { get; set; }
        public DbSet<IPORTAL_FP_ROW> IPORTAL_FP_ROW { get; set; }
        public DbSet<IPORTAL_FP_STYLE> IPORTAL_FP_STYLE { get; set; }
        public DbSet<IPORTAL_PC_DATASET> IPORTAL_PC_DATASET { get; set; }
        public DbSet<IPORTAL_PC_FILE> IPORTAL_PC_FILE { get; set; }
        public DbSet<IPORTAL_PP_DATASET> IPORTAL_PP_DATASET { get; set; }
        public DbSet<IPORTAL_PP_FILE> IPORTAL_PP_FILE { get; set; }
        public DbSet<IPORTAL_SCALE> IPORTAL_SCALE { get; set; }
        public DbSet<IPORTAL_SDTM_VARIABLE> IPORTAL_SDTM_VARIABLE { get; set; }
        public DbSet<IPORTAL_STUDY> IPORTAL_STUDY { get; set; }
        public DbSet<IPORTAL_STUDY_DESIGN> IPORTAL_STUDY_DESIGN { get; set; }
        public DbSet<IPORTAL_STUDY_TYPE> IPORTAL_STUDY_TYPE { get; set; }
        public DbSet<IPORTAL_SUBMISSION> IPORTAL_SUBMISSION { get; set; }
        public DbSet<IPORTAL_SUBMISSION_TYPE> IPORTAL_SUBMISSION_TYPE { get; set; }
        public DbSet<IPORTAL_VARIABLE_MAPPING> IPORTAL_VARIABLE_MAPPING { get; set; }
        public DbSet<SYSTEM_USER> SYSTEM_USER { get; set; }
    }
}
