//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPortal.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_USER
    {
        public SYSTEM_USER()
        {
            this.FPTOOLS_PROJECT = new HashSet<FPTOOLS_PROJECT>();
        }
    
        public int USER_ID { get; set; }
        public string USER_NAME { get; set; }
    
        public virtual ICollection<FPTOOLS_PROJECT> FPTOOLS_PROJECT { get; set; }
    }
}
