//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SasJobs.Api.BackgroundWorker {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BackgroundWorker.ISasJobsService", CallbackContract=typeof(SasJobs.Api.BackgroundWorker.ISasJobsServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ISasJobsService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISasJobsService/BeginJob")]
        void BeginJob(SasJobs.Messages.JobSettings settings);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISasJobsService/BeginJob")]
        System.Threading.Tasks.Task BeginJobAsync(SasJobs.Messages.JobSettings settings);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISasJobsServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISasJobsService/OnProgress")]
        void OnProgress(SasJobs.Messages.JobFeedback feedback);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISasJobsService/OnCompleted")]
        void OnCompleted(SasJobs.Messages.JobFeedback feedback, string xmlResult);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISasJobsServiceChannel : SasJobs.Api.BackgroundWorker.ISasJobsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SasJobsServiceClient : System.ServiceModel.DuplexClientBase<SasJobs.Api.BackgroundWorker.ISasJobsService>, SasJobs.Api.BackgroundWorker.ISasJobsService {
        
        public SasJobsServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SasJobsServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SasJobsServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SasJobsServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SasJobsServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void BeginJob(SasJobs.Messages.JobSettings settings) {
            base.Channel.BeginJob(settings);
        }
        
        public System.Threading.Tasks.Task BeginJobAsync(SasJobs.Messages.JobSettings settings) {
            return base.Channel.BeginJobAsync(settings);
        }
    }
}
